# $Id: Makefile,v 1.4 2005/04/06 18:52:22 wam Exp $
# Makefile for xsl-grep

SRC= xsl-grep.py
PROG= xsl-grep
DESTDIR=/usr/local/
BIN=${DESTDIR}/bin
INSTALL=install

all:
	: "Nothing to be done to make ${PROG}"

install: FRC
	${INSTALL} -m 755 ${SRC} ${BIN}/${PROG}

clean: FRC

FRC:


